### ISSUE TITLE
Static map URLs do not include correct zoom level.

### ISSUE THREAD

**Issue by powerbuoy** [EarthPeople/WP-Simple-Fields-Map-Extension#2]
The static map URLs returned by simlple_fields_value('map')['static_maps']['some_size'] will always contain a zoom level of 16 regardless of what the user sets in the admin.

I've tried to fix the issue myself by changing line 356 from:

```
"zoom"      => $options["static_maps_zoom"]
```

To:

```
"zoom"      => !empty($val['preferred_zoom']) ? $val['preferred_zoom'] : $options["static_maps_zoom"]
```

Which seems to work, but I'm not sure if it breaks something else.

Also, empty("0") returns true for some reason so setting a zoom level to 0 will still result in the default being used.

**Comment by bonny** [comment]
thanks for the report. should be fixed in 1.3.1.
